### PR TITLE
Improvments related to static analisis

### PR DESCRIPTION
**Pull request by Guts**
Hello,

I'm working at Oslandia (as @haubourg was) and we would like to contribute to your plugin in order to deploy it in an automatic way. Running code static analisis, we've met some warnings and errors, so here come our contribution to fix them all.

In this PR:

- fix errors and warnings spotted by flake8: unused imports, etc.
- use PyQGIS recomendeed imports (from qgis.PyQt instead of from PyQt5)
- sorting imports (isort) to avoid conflicts or hidden imports
- add Github Actions to perform static analisis (flake8) for pull requests and commits to master

### CODE REVIEW

**Comment by enricofer** [comment]
your edits are welcome. feel free to PR.

**Comment by Guts** [comment]
> your edits are welcome. feel free to PR.

Thank you! I'm finishing to complete this PR, then I'll mark it as ready for review.

**Comment by Guts** [comment]
@enricofer I've fixed a bunch of problems spotted by flake8, particularly on imports side. Please check it.

But there is still PyQGIS 2 code with `QgsMapLayerRegistry` in 3 methods at those lines: https://github.com/Guts/redLayer/blob/flake8/redLayerModule.py#L523-L544. So, an exception is systematically raised and ignored and I suggest you fix that since the plugin is only for QGIS 3 (as stated in the metadata.txt).

**Comment by enricofer** [comment]
fixed
https://github.com/enricofer/redLayer/commit/e54050b92cc9c1dd1b5d64e6ebea19ae1f385c04

Il giorno lun 22 feb 2021 alle ore 17:30 Julien <notifications@github.com>
ha scritto:

**Pull request merged**
